languageCode = "en"
languageName = "English"
weight = 1
title = "Andres Navarro Pedregal"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Andres Navarro Pedregal"
  email = "contact@andresnav.com"
  image = "img/blowfish_logo.png"
  headline = "A powerful, lightweight theme for Hugo."
  bio = "A powerful, lightweight theme for Hugo."
  links = [
    { linkedin = "https://linkedin.com/in/andresnav" },
    { github = "https://github.com/andres-nav" },
  ]
