languageCode = "en"
languageName = "English"
weight = 1
title = "Andres Navarro Pedregal"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = ""

[params.author]
  name = "Andres Navarro Pedregal"
  email = "contact@andresnav.com"
  image = "img/profile.png"
  headline = "Build cloud solutions with AWS"
  bio = "Build cloud solutions with AWS"
  links = [
    { linkedin = "https://linkedin.com/in/andresnav" },
    { github = "https://github.com/andres-nav" },
  ]
